// Code generated by SQLBoiler 4.13.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

var TableNames = struct {
	Carts             string
	Orders            string
	Permissions       string
	ProductCategories string
	ProductDiscounts  string
	Products          string
	Roles             string
	RolesPermissions  string
	Tokens            string
	Users             string
	UsersRoles        string
}{
	Carts:             "carts",
	Orders:            "orders",
	Permissions:       "permissions",
	ProductCategories: "product_categories",
	ProductDiscounts:  "product_discounts",
	Products:          "products",
	Roles:             "roles",
	RolesPermissions:  "roles_permissions",
	Tokens:            "tokens",
	Users:             "users",
	UsersRoles:        "users_roles",
}
